#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SOURCES_FILE = path.join(__dirname, 'key-sources.json');
const OUTPUT_FILE = path.join(ROOT, 'known-keys.js');

async function fetchUrl(url) {
    const res = await fetch(url);
    if (!res.ok) throw new Error(`HTTP ${res.status}: ${url}`);
    return Buffer.from(await res.arrayBuffer());
}

async function fetchKeyserver(keyserver, fingerprint) {
    const fp = fingerprint.replace(/\s/g, '');
    const url = `https://${keyserver}/vks/v1/by-fingerprint/${fp}`;
    const res = await fetch(url);
    if (!res.ok) throw new Error(`HTTP ${res.status}: ${url}`);
    return Buffer.from(await res.arrayBuffer());
}

async function buildDb(sources) {
    const { readKeys } = await import('openpgp');
    const db = {};
    const summary = [];

    for (const source of sources) {
        try {
            let keyData;
            if (source.strategy === 'url') {
                keyData = await fetchUrl(source.url);
            } else if (source.strategy === 'keyserver') {
                keyData = await fetchKeyserver(source.keyserver || 'keys.openpgp.org', source.fingerprint);
            } else {
                throw new Error(`Unknown strategy: ${source.strategy}`);
            }

            let keys;
            try {
                keys = await readKeys({ binaryKeys: keyData });
            } catch (_) {
                keys = await readKeys({ armoredKeys: keyData.toString('utf8') });
            }
            if (!keys || keys.length === 0) throw new Error('No keys found in response');

            for (const key of keys) {
                const keyID = key.getKeyID().toHex().toLowerCase();
                const fingerprint = key.getFingerprint().toUpperCase();
                db[keyID] = {
                    distro: source.distro,
                    label: source.label,
                    fingerprint,
                    armoredKey: key.armor()
                };
                summary.push({ distro: source.distro, label: source.label, keyID });
                console.log(`  ✓ ${source.distro}: ${source.label} (${keyID})`);
            }
        } catch (err) {
            console.error(`  ✗ FAILED: ${source.distro} — ${source.label}: ${err.message}`);
            summary.push({ distro: source.distro, label: source.label, error: err.message });
        }
    }

    return { db, summary };
}

function writeOutput(db, timestamp) {
    const keyCount = Object.keys(db).length;
    return `// Auto-generated by scripts/fetch-keys.js — do not edit manually
// Last updated: ${timestamp}  Keys: ${keyCount}
window.KnownKeys = (function() {
  const db = ${JSON.stringify(db, null, 2)};
  return {
    lookup: function(keyID) {
      return db[keyID] || null;
    }
  };
})();
`;
}

async function main() {
    const sources = JSON.parse(fs.readFileSync(SOURCES_FILE, 'utf8'));
    console.log(`Fetching ${sources.length} key sources...`);

    const { db, summary } = await buildDb(sources);
    const timestamp = new Date().toISOString();
    const content = writeOutput(db, timestamp);

    fs.writeFileSync(OUTPUT_FILE, content);
    console.log(`\nWrote ${Object.keys(db).length} keys to ${OUTPUT_FILE}`);

    const failed = summary.filter(s => s.error);
    if (failed.length > 0) {
        console.error(`\n${failed.length} source(s) failed:`);
        failed.forEach(f => console.error(`  - ${f.distro}: ${f.error}`));
        process.exit(1);
    }
}

if (require.main === module) {
    main().catch(err => { console.error('Fatal:', err.message); process.exit(1); });
}

module.exports = { buildDb, writeOutput, fetchUrl, fetchKeyserver };
